// frontend/src/components/podcast-list-element.tsx
import { useMemo } from "react";
import PauseIcon from "../assets/icons/pause-icon";
import PlayIcon from "../assets/icons/play-icon";
import { Podcast } from "../lib/types";
import useAppStore from "../lib/store";

const PodcastListElement = ({ podcast }: { podcast: Podcast }) => {
  const {
    setCurrentPodcast,
    currentPodcast,
    audioElement,
    status,
    setView,
    play,
    pause,
    stop,
  } = useAppStore();

  const isSelected = useMemo(
    () => currentPodcast?.id === podcast.id,
    [currentPodcast, podcast],
  );

  const style = `flex items-center justify-between p-4 rounded-md ${
    isSelected ? "bg-slate-900/60" : "bg-slate-900"
  }  backdrop-blur-3xl hover:ring-1 ring-indigo-600/60`;

  const handleOnClick = () => {
    if (!audioElement) return;

    if (isSelected && currentPodcast?.id === podcast.id) {
      if (status === "playing") {
        pause();
      } else {
        play();
      }
    }

    // if user clicks on a different podcast than the one playing or paused, set the new podcast
    if (currentPodcast?.id !== podcast.id) {
      stop();
      setCurrentPodcast(podcast);
      play();
      setView("podcast-detail");
    }
  };

  return (
    <li className={style}>
      <span className="text-white cursor-default">{podcast.title}</span>
      <button
        className="p-2 rounded-md cursor-pointer bg-slate-800 hover:bg-slate-700"
        onClick={handleOnClick}
      >
        {status === "playing" && isSelected ? (
          <PauseIcon className="stroke-white" />
        ) : (
          <PlayIcon className="stroke-white" />
        )}
      </button>
    </li>
  );
};

export default PodcastListElement;

// frontend/src/lib/PodcastListElement.svelte
<script lang="ts">
  import Pause from './icons/Pause.svelte';
  import Play from './icons/Play.svelte';
  import { store } from './store/store.svelte';

  let { podcast } = $props();

  let isSelected = $derived(store.currentPodcast?.id === podcast.id);

  const handleOnClick = () => {
    if (isSelected && store.currentPodcast?.id === podcast.id) {
      if (store.status === 'playing') {
        store.pause();
      } else {
        store.play();
      }
    }

    if (store.currentPodcast?.id !== podcast.id) {
      store.reset();
      store.currentPodcast = podcast;
      store.view = 'podcast-detail';
    }
  };
</script>

<li
  class="flex items-center justify-between p-4 rounded-md backdrop-blur-3xl hover:ring-1 ring-indigo-600/60 {isSelected
    ? 'bg-slate-900/60'
    : 'bg-slate-900'}"
>
  <span class="text-white cursor-default">{podcast.title}</span>
  <button
    class="p-2 rounded-md cursor-pointer bg-slate-800 hover:bg-slate-700"
    onclick={handleOnClick}
    aria-label="play"
    title="Play"
  >
    {#if store.status === 'playing' && isSelected}
      <Pause class="text-white" />
    {:else}
      <Play class="text-white" />
    {/if}
  </button>
</li>
